wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/1.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/2.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/3.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/4.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/5.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/Advanced.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/Amateur.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/Beginner.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/Boss.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/Major.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/Master.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/Professional.png
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/body.jpg
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/content.jpg
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/footer2.gif
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/header.jpg
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/header7.jpg
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/header8.jpg
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/menubottom.jpg
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/menuhover.gif
