wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/challenge.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/challenge.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/correct.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/create_gymkhana.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/create_message.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/create_message.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/create_team.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/create_user.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/edit_team.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/error.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/error.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/gymkhana.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/gymkhana_information.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/images/
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/join_team.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/list_event.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/list_event.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/list_message.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/list_response.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/list_response.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/list_skipped_challenge.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/list_team.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/list_user.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/login.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/monitoring.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/my_standings.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/num_messages.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/overall_standings.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/overall_standings.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/overlib.js
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/reply_message.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/show_clue.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/show_clues.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/show_gymkhana.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/show_team.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/show_team.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/show_user.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/solution.html
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/solution.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/style.css
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/team_member_has_team.json
wget http://libregeosocial.org/libregeosocial/apps/_gymkhana/templates/team_member_previous_teams.json
